### PR TITLE
Update DUI translation

### PR DESCRIPTION
**Pull request by Leex00G**
NitrogenSettings: Update Simplified Chinese translations
Update DUI translation

### CODE REVIEW

**Comment by GangLeeGithub** [comment]
NitrogenSettings: Update Simplified Chinese translations

**Comment by GangLeeGithub** [comment]
Update DUI translation

**Comment by GangLeeGithub** [comment]
NitrogenSettings: Update zh_rCN translations

**Comment by GangLeeGithub** [comment]
Update DUI translation

**Comment by Leex00G** [comment]
Fix some translation problems (Final)

**Comment by Leex00G** [comment]
Can you pass it?（可以通过吗？）

**Comment by Leex00G** [comment]
Pass that latest commits

**Pull request closed without merging**
