### PR TITLE
Update nitrogen_strings.xml

### PR DESCRIPTION
**Pull request by rbarat**
Hi,

I started working on slovak translations. Please prepare
android_packages_apps_NitrogenSettings/res/values-sk\nitrogen_strings.xml

Then I will translate it on Github pages directly. So far I have not translated more because I do not know if you accept my request.

Please accept my request. I would like to supplement Slovak translation of this great ROM.

Thanks

Robert - rbarat07@gmail.com

### CODE REVIEW

**Comment by xyyx** [comment]
You need to make this folder in pull request and make full translation

**Comment by rbarat** [comment]
Tnak you for answer - please tell me how to translate nitrogen_strings.xml file in PC? What editor should I use? I used Notepad ++, but now is not suitable now. Hardly looking up translations in XML code.

Thanks

**Comment by xyyx** [comment]
Notepad++ good choice.

**Comment by rbarat** [comment]
OK, try prepare full translation at evening, then will try to make pull request.
Thank you much.
Robert

**Pull request closed without merging**
