### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by ghost**
Now everything should be correct :)

### CODE REVIEW

**Comment by xyyx** [comment]
packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:34: warning: string 'hex_hint' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:316: warning: string 'action_value_default_action' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:317: warning: string 'action_value_select_app' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:318: warning: string 'action_value_custom_action' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:319: warning: string 'action_value_back' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:320: warning: string 'action_value_home' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:321: warning: string 'action_value_search_assist' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:322: warning: string 'action_value_recent_apps' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:323: warning: string 'action_value_voice_search' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:324: warning: string 'action_value_menu' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:701: warning: string 'static_header_provider' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:702: warning: string 'daylight_header_provider' marked untranslatable but exists in locale 'it'

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:50: error: Apostrophe not preceded by \ (in Widget dell\ 'orologio)

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:55: error: Apostrophe not preceded by \ (in Termina l'app in sovraimpressione premendo il tasto indietro)

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:57: error: Apostrophe not preceded by \ (in Tempo necessario per terminare l'applicazione)

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:111: error: Apostrophe not preceded by \ (in Usa l\ 'MTP invece di ricaricare)

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:112: error: Apostrophe not preceded by \ (in Abiita l\ 'MTP inbece della ricarica dopo aver connesso il dispositivo al Computer)

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:140: error: Apostrophe not preceded by \ (in Scambia l\ 'orientamento dei pulsanti del volume)

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:141: error: Apostrophe not preceded by \ (in Aggiusta l\ 'orientamento dei pulsanti del volume in base alla rotazione corrente)

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:166: error: Apostrophe not preceded by \ (in Nascondi le frecce dell\ 'indicatore di rete)

packages/apps/NitrogenSettings/res/values-it/nitrogen_strings.xml:175: error: Apostrophe not preceded by \ (in Doppio tocco nelle shortcut in alto nel terzo o in fondo nell'area della schermata di blocco per speg

**Comment by ghost** [comment]
I need to make it again or just do another commit?

**Comment by ghost** [comment]
Also, I should translate the one "untranslatable"?

**Comment by xyyx** [comment]
Yes. You need new commit and don't touch untranslatable. And try build before push

**Pull request merged**
