### PR TITLE
Update LS weather strings (english)

### PR DESCRIPTION
**Pull request by calebcabob**

### CODE REVIEW

**Comment by xyyx** [comment]
Are you joking, dude? I removed it, because I replaced weather.

**Comment by calebcabob** [comment]
I was picking weather from you and noticed you didn't have those strings in main, but had them in the other languages - was just trying to help ya. No prob

**Comment by xyyx** [comment]
This strings are useless. See code.
https://github.com/nitrogen-project/android_packages_apps_NitrogenSettings/commit/9f818f405f6056a8c29d1a51a08a1ce26ad798b1

**Comment by calebcabob** [comment]
Your arrays are still calling for them, that's why it was confusing

**Comment by xyyx** [comment]
Maybe. Made it quickly without cleaning

**Comment by calebcabob** [comment]
I've gotta say, very nice job with weather man.  Must have been a bitch. All working very smoothly - very glad to see it updates again!

**Pull request closed without merging**
