### PR TITLE
NitrogenSettings: Redo DeviceParts availability

### PR DESCRIPTION
**Pull request by 4j17h**
Change-Id: I82de669f7e1671f02cb1fa8d244be84c10e6b36b

### CODE REVIEW

**Comment by 4j17h** [comment]
This way we can avoid creating multiple preferences to support different device specific settings app.

Also added support for _org.lineageos.settings.device_ package which is used by most devices.

**Comment by xyyx** [comment]
Yeah! Good code. But can you rework it with for? 
for (int i=0; i < targetPackage.length; i++)
 and your code.  instead manually using array's string.

**Comment by 4j17h** [comment]
> Yeah! Good code. But can you rework it with for?
> for (int i=0; i < targetPackage.length; i++)
> and your code. instead manually using array's string.

oh yeah, that's neat. Thanks, will push changes.

**Comment by 4j17h** [comment]
ok so I have tested & force-pushed with the suggested changes.

**Comment by xyyx** [comment]
Added without merging. Thanks!

**Pull request closed without merging**
