### PR TITLE
NitrogenSettings: Update Simplified Chinese translations

### PR DESCRIPTION
**Pull request by Leex00G**
NitrogenSettings: Simplified Chinese translations

### CODE REVIEW

**Comment by ghost** [comment]
Hi.(嗨.)
1.Title error,this is the Chinese language.(标题错啦，这是中文。而不是CS/SK)
2.完全复制文档，完成后一个提交。
3.1-49 lines?(1-49行？)

**Comment by Leex00G** [comment]
Sorry,now is ok

**Comment by Leex00G** [comment]
Now it's done

**Comment by Leex00G** [comment]
@shangguanfengye我重新提交了，麻烦审核下

**Comment by Leex00G** [comment]
我已经重新提交了

**Pull request closed without merging**
